config/routes.rb
Rails.application.routes.draw do
 root to: 'homes#top'
 get 'about' => 'homes#about'
 get 'search' => 'searches#search'
 devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 resources :musics do
  resource :favorites, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
 end

  resources :users, only: [:show] do
    get 'favorites' => "users#favorites"
  end
  resources :users do
  #memberでidを取得する
   member do
      get :follows, :followers
    end
  resource :relationships, only: [:create, :destroy]
   get 'followings' => 'relationships#followings', as: 'followings'
   get 'followers' => 'relationships#followers', as: 'followers'
   get 'musics' => 'users#music'
  end

  resources :contacts, only: [:new, :create]

end

app/models/favorite.rb
class Favorite < ApplicationRecord

belongs_to :user
belongs_to :music

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    # music_idを指定する
    @music = Music.find(params[:music_id])
    favorite = current_user.favorites.new(music_id: @music.id)
    favorite.save
  end

  def destroy
    @music = Music.find(params[:music_id])
    favorite = current_user.favorites.find_by(music_id: @music.id)
    favorite.destroy
  end

end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite-btn.html.erb
 <% if music.favorited_by?(current_user) %>
    <p>
      <%= link_to music_favorites_path(music), method: :delete, remote: true do %>
        ♥<%= music.favorites.count %> いいね
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to music_favorites_path(music), method: :post, remote: true do %>
        ♡<%= music.favorites.count %> いいね
      <% end %>
    </p>
  <% end %>

app/views/favorites/_favorite.html.erb
 <% if music.favorited_by?(current_user) %>
    <p>
      <%= link_to music_favorites_path(music), method: :delete, remote: true do %>
        ♥<%= music.favorites.count %> いいね
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to music_favorites_path(music), method: :post, remote: true do %>
        ♡<%= music.favorites.count %> いいね
      <% end %>
    </p>
  <% end %>

app/views/favorites/create.js.erb
$('#favorite_buttons_<%= @music.id %>').html("<%= j(render "favorites/favorite", music: @music) %>");

app/views/favorites/destroy.js.erb
$('#favorite_buttons_<%= @music.id %>').html("<%= j(render "favorites/favorite", music: @music) %>");