config/routes.rb
Rails.application.routes.draw do
 root to: 'homes#top'
 get 'about' => 'homes#about'
 get 'search' => 'searches#search'
 devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 resources :musics do
  resource :favorites, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
 end

  resources :users, only: [:show] do
    get 'favorites' => "users#favorites"
  end
  resources :users do
  #memberでidを取得する
   member do
      get :follows, :followers
    end
  resource :relationships, only: [:create, :destroy]
   get 'followings' => 'relationships#followings', as: 'followings'
   get 'followers' => 'relationships#followers', as: 'followers'
   get 'musics' => 'users#music'
  end

  resources :contacts, only: [:new, :create]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :musics, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_musics, through: :favorites, source: :music

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人


  attachment :profile_image

  def self.search(search,word)
    if word == ""
      @user = []
    elsif search == "perfect_match"
      @user = User.where(name: word)
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end
  validates :name,  presence: true
  validates :name, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @musics = @user.musics.page(params[:page]).reverse_order
    # id以外の値を取得するためwhereを使用　フォローしている人の楽曲をマイページのタイムラインに表示
    @feeds = Music.where(user_id: [current_user.id, *current_user.following_user_ids]).order(created_at: :desc)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: 'ユーザー情報を編集しました。'
    else
      render :edit
    end
  end

  def music
    @user = User.find(params["user_id"])
    # userが投稿した曲の表示
    @musics = @user.musics.page(params[:page]).reverse_order
    # id以外の値を取得するためwhereを使用　フォローしている人の楽曲をマイページのタイムラインに表示
    @feeds = Music.where(user_id: [current_user.id, *current_user.following_user_ids]).order(created_at: :desc)
    @following_users = @user.following_user
    @follower_users = @user.follower_user
  end

  def favorites
    @user = User.find(params["user_id"])
    # userがいいねした楽曲をfavoriteと定義
    favorites = Favorite.where(user_id: @user.id).pluck(:music_id)
    @favorite_musics = Music.find(favorites)
  end

  def follows
    # フォロー一覧ページ
    user = User.find(params[:id])
    @users = user.following_user.page(params[:page]).per(3).reverse_order
  end

  def followers
    # フォロワー一覧ページ
    user = User.find(params[:id])
    @users = user.follower_user.page(params[:page]).per(3).reverse_order
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/views/users/edit.html.erb
<h4 class="mx-auto">
  <% if @user.errors.any? %>
    <Strong><%= @user.errors.count %>  errors occur!  :</Strong>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
  <% end %>
</h4>

<div class="container">
  <div class="row">
    <div class="mx-auto">
      <div class="mx-auto">
        <h2>プロフィール編集</h2>
      </div>
      <div class="container form-contents mt-4">
        <%= form_with model:@user, local:true do |f| %>

          <div class="field form-group row">
            <div class="col-md-12 mb-6 mt-3">
              <label for="inputName">お名前　</label>
              <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
            </div>
          </div>
          <div class="field form-group row">
            <div class="col-md-12 mb-6 mt-3">
              <label for="inputName">自己紹介　</label>
              <%= f.text_field :introduction, size: "30x3", autofocus: true,  placeholder:"自己紹介"%>
            </div>
          </div>
         <div class="field form-group row">
            <div class="col-md-12 mb-6 mt-3">
              <label for="inputImage">プロフィール画像　</label>
              <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
            </div>
          </div>
          <div class="actions mt-5">
            <%= f.submit "変更を保存",class:"btn btn-primary btn-xl" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/favorite.html.erb
<div class="album py-5 bg-light">
<div class="container">
  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    <div class="mainContents col-sm-9 col-sm-push-3 col-md-12 col-md-push-3 ">
      <h2 class="subtitle pb-4">新着楽曲</h2>
        <div class="row">
<%# binding.pry %>
              <div class="col-md-4 pb-4">
                <div class="card shadow-sm"style="height: 21rem;">
                  <%= link_to music_path(music.id) do %>
                    <%= attachment_image_tag(music, :song_image, :fill, 348, 150, fallback: "no_image.jpg") %>
                  <% end %>
                  <br><p class="mx-auto"><%= link_to music.title, music_path(music.id) %> / <%= link_to music.user.name, user_path(music.user.id) %></p>
                  <p class="mx-auto"><audio src= "<%= "#{music.song}" %>" controls=""></p>
                </div>
              </div>
            <% end %>
          </div>
      </div>
    </div>
  </div>
  </div>

app/views/users/favorites.html.erb
<div class="py-5 bg-light">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      <div class="mainContents col-sm-9 col-sm-push-3 col-md-12 col-md-push-3 ">
        <h2 class="subtitle pb-4">いいねした楽曲一覧</h2>
          <div class="row">
            <%# binding.pry %>
              <% @favorite_musics.each do |music| %>
                <div class="col-md-4 pb-4">
                  <div class="card shadow-sm"style="width: 100%; height: 28rem;">
                    <div class="jacket-image">
                      <%= link_to music_path(music.id) do %>
                        <%= attachment_image_tag(music, :song_image, fallback: "no_image.jpg", class: "jacket-image") %>
                      <% end %>
                    </div>
                    <br>
                    <div class="favorite-content">
                      <p class="mx-auto"><%= link_to music.title, music_path(music.id) %> / <%= link_to music.user.name, user_path(music.user.id) %></p>
                      <p class="mx-auto"><audio src= "<%= "#{music.song}" %>" controls=""></p>
                    </div>
                  </div>
                </div>
              <% end %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h1 class="mt-5 mb-5">フォロワー一覧</h1>
  </div>
  <div class="row justify-content-center bg-light">
    <% @users.each do |user| %>
      <div class="w-100 mb-3">
        <%= link_to user_path(user) do %>
        <h4><%= user.name %></4>
        <div>
          <%= attachment_image_tag user, :profile_image, class: "rounded-circle",  size: "100x100", format: 'jpeg', fallback: "no_image.jpg", class: "mb-3 mt-3 ml-3 rounded-circle" %>
          <h6><%= user.introduction %></h6>
          <br>
          <br>
        </div>
          <% end %>
      </div>
      <% end %>
  </div>
    <%= paginate @users %>
</div>

app/views/users/follows.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h1 class="mt-5 mb-5">フォロー一覧</h1>
  </div>
  <div class="row justify-content-center bg-light">
    <% @users.each do |user| %>
      <div class="w-100 mb-3 ">
        <%= link_to user_path(user) do %>
        <h4><%= user.name %></h>
        <div>
          <%= attachment_image_tag user, :profile_image, size: "100x100", format: 'jpeg', fallback: "no_image.jpg", class: "mb-3 mt-3 ml-3 rounded-circle" %>
          <h6><%= user.introduction %></h6>
          <br>
          <br>
        </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <%= paginate @users %>
</div>

app/views/users/music.html.erb
<div class="container" >
 <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3" >
    <div class="mainContents col-sm-9 col-sm-push-3 col-md-12 col-md-push-3" >
      <h2 class="subtitle pb-4 user-show-text"><%= @user.name %>さんの投稿一覧</h2>
        <hr>
        <div class="row" >
          <% @musics.each do |music| %>
          <div class="col-md-4 pb-4">
           <div class="card shadow-sm " style="width: 100%; height: 38rem;" >
            <%= link_to music_path(music.id) do %>
              <%= attachment_image_tag(music, :song_image, fallback: "no_image.jpg", class: "jacket-image rounded-circle" )  %>
              <% end %><br>
              <p>曲名：<%= link_to music.title,  music_path(music.id) %></p>
              <p><%= music.caption %></p></br>
              <!--carrierwave audioの再生プレイヤーの表示-->
              <p class="mx-auto"><audio src= "<%= "#{music.song}" %>" controls=""></audio></p>
              <p class="mx-auto">自己評価</p>
              <p class="text-center">
              <!--評価についての記述-->
              <h5 class="music-evaluation" data-score="<%= music.evaluation %>"></h5></p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <hr>
</div>

<script>
  $('.music-evaluation').empty();
  $('.music-evaluation').raty({
    readOnly: true,
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    score: function() {
      return $(this).attr('data-score');
    },
  });
</script>

app/views/users/show.html.erb
<div>
  <h2><%= flash[:notice]  %></h2>
</div>
<div class="show-name">
  <!--currentuserのみ表示-->
    <% if @user == current_user %>
  <h3>ようこそ<%= @user.name %>さん！</h3>
    <% end %></br>
</div>
<div class="container">
  <div class="row">
    <div class="col-lg-6" >
      <div class="show-image">
        <%= attachment_image_tag @user, :profile_image, class: "rounded-circle", size: "250x250", format: 'jpeg', fallback: "no_image.jpg" %>
      </div>
    </div>
    <div class="col-lg-6 show-content">
      <% if @user.id == current_user.id %>
        <p><%= link_to "プロフィール編集", edit_user_path(@user) %></p>
      <% end %>
      <p>ユーザーネーム：<%= link_to @user.name, user_path(@user.id) %></p>
      <p>自己紹介<br><%= @user.introduction %></p>
      <br>
      <h5><%= @user.name %>さんの<%= link_to '楽曲一覧', user_musics_path(:user_id => @user.id) %></h5><br>
        <%= link_to "いいねした楽曲", user_favorites_path(:user_id => @user.id) %>
      <br>
      <br>
      <p><%= link_to "フォロー中", follows_user_path(@user) %> / <%= link_to "フォロワー", followers_user_path(@user) %></p>
        <% if current_user != @user %>
          <% if current_user.following?(@user) %>
          <%= link_to 'フォロー外す', user_relationships_path(@user.id), method: :delete, class: "btn-sm btn-danger" %>
        <% else %>
          <%= link_to 'フォローする', user_relationships_path(@user.id), method: :POST, class:"btn-sm btn-success" %>
          <% end %>
        <% end %>
      <br>
      <br>
      <br>
    </div>
  </div>
</div>
<!--currentuserのみ表示-->
<% if @user == current_user %>
<div class="container" >
 <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 show-timeline" >
    <div class="mainContents col-sm-12 col-md-12" >
       <h3 class="subtitle pb-4 user-show-text">タイムライン（フォローしている人の楽曲）</h3>
      <hr>
      <div class="row bg-light" >
        <% @feeds.each do |music| %>
        <div class="col-md-4 pb-4">
         <div class="card shadow-sm" style="width: 100%; height: 38rem;"  >
          <div class="mx-auto">
            <%= link_to music_path(music.id) do %>
              <%= attachment_image_tag(music, :song_image, fallback: "no_image.jpg" , class: "jacket-image") %>
            <% end %><br>
          </div>
            <div class="time-line-content mx-auto">
              <p>@<%= link_to music.user.name, user_path(music.user.id) %></p>
              <p>曲名：<%= music.title %></p>
              <p>曲について：<%= music.caption %></p></br>
              <p class="mx-auto"><audio src= "<%= "#{music.song}" %>" controls="", class: "audio-form")></audio></p>
              <p class="mx-auto">自己評価</p>
              <p class="text-center">
              <h5 class="music-evaluation" data-score="<%= music.evaluation %>"></h5></p>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
  <hr>
</div>
<% end %>
<script>
  $('.music-evaluation').empty();
  $('.music-evaluation').raty({
    readOnly: true,
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    score: function() {
      return $(this).attr('data-score');
    },
  });
</script>

<div class="container col-2 mt-5 mx-auto">
  <span>
    <%= paginate @musics %>
  </span>
</div>