config/routes.rb
Rails.application.routes.draw do
 root to: 'homes#top'
 get 'about' => 'homes#about'
 get 'search' => 'searches#search'
 devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 resources :musics do
  resource :favorites, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
 end

  resources :users, only: [:show] do
    get 'favorites' => "users#favorites"
  end
  resources :users do
  #memberでidを取得する
   member do
      get :follows, :followers
    end
  resource :relationships, only: [:create, :destroy]
   get 'followings' => 'relationships#followings', as: 'followings'
   get 'followers' => 'relationships#followers', as: 'followers'
   get 'musics' => 'users#music'
  end

  resources :contacts, only: [:new, :create]

end

app/models/music.rb
class Music < ApplicationRecord

mount_uploader :song, AudiofileUploader

  belongs_to :user
  attachment :song_image
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def self.search(search, word)
    if word == ""
      @music = []
    elsif search == "perfect_match"
      @music = Music.where(title: word)
    elsif search == "partial_match"
      @music = Music.where("title LIKE?","%#{word}%")
    else
      @music = Music.all
    end
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :evaluation, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }

  validates :title, length: { in: 2..50 }, presence: true
  validates :caption, length: { in: 2..100 }, presence: true
  validates :song, presence: true
  validates :song_image, presence: true

end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :find_music, only: [:show, :edit, :update]

  def show
    @comment = Comment.new
  end

  def index
    @musics = Music.page(params[:page]).reverse_order
    @user = current_user
    #ランキング機能music_idをもってきて、favoritecountを表示。表示数を3件
    @all_ranks = Music.find(Favorite.group(:music_id).order('count(music_id) desc').limit(3).pluck(:music_id))
  end

  def new
    # Musicの新規投稿について定義
    @music = Music.new
  end

  def create
    @music = Music.new(music_params)
    # current_userをuserに紐づいているmusicと結びつける
    @music.user_id = current_user.id
    if @music.save
      redirect_to musics_path, notice: '投稿しました。'
      #binding.pry
    else
      render :new
    end
  end


  def edit
  end

  def update
    if @music.update(music_params)
      redirect_to music_path(@music.id), notice: '編集しました。'
    else
      render :edit
    end
  end

  def destroy
    @music = Music.find(params[:id])
    @music.destroy
    redirect_to musics_path
  end

  private
  def music_params
    params.require(:music).permit(:title, :caption, :song, :song_image, :user_id, :evaluation)
  end

  def find_music
    @music = Music.find(params[:id])
  end

end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/views/musics/edit.html.erb
<h4 class="mx-auto">
  <% if @music.errors.any? %>
    <Strong><%= @music.errors.count %>  errors occur!  :</Strong>
      <ul>
        <% @music.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
  <% end %>
</h4>
<div class="container">
  <div class="row ">
    <div class="mx-auto" >
      <div class="mx-auto">
          <h2 class="field form-group row">
            <div class="mx-auto col mb-3">
              投稿した曲の編集
            </div>
          </h2>
          <%= form_with model: @music, local:true do |f| %>
            <div class="field form-group row">
              <div class="mx-auto col mb-3">
                <%= f.label :title, '曲名' %>
                <%= f.text_field :title,autofocus: true, class:"form-control", required: true %>
              </div>
            </div>
            <br>
            <div class="field form-group row">
              <div class="mx-auto col mb-3">
                <%= f.label :caption, '説明' %>
                <%= f.text_field :caption,autofocus: true, class:"form-control" , required: true%>
              </div>
            </div>
            <br>
            <div class="field form-group row">
              <div class="mx-auto col mb-3">
                <%= f.label :song_image, 'ジャケ写など' %><br>
                <%= f.attachment_field :song_image,autofocus: true, required: true %><br>
                <br>
              </div>
            </div>
            <div class="field form-group row">
              <div class="mx-auto col mb-3">
                <%= f.label :song, '曲の選択' %><br>
                <%= f.file_field :song , :size => 140,autofocus: true, required: true %><br><br>
                <p6><strong>※外部サイトは使用できません。また、他人の転載は禁止です。</strong></p6>
              </div>
            </div>
            <br>
             <div class="field form-group row">
              <div class="mx-auto col mb-3">
                <div id="evaluate_stars">
                  <%= f.label :evaluation, '自己評価　　' %>
                </div>
              </div>
            </div>
            <br>
            <div class="container ">
              <div class="actions">
                <%= f.submit "編集を保存", class: "btn btn-primary btn-xl" %>
              </div>
                <% end %>
            </div>
          <br>
          <br>
          <%= link_to "曲詳細に戻る", music_path(@music.id) %><span> |</span>
          <%= link_to "曲一覧に戻る", "/musics" %>
        </def>
      </div>
    </div>
  </div>
</div>
<script>
  $('#evaluate_stars').raty({
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    scoreName: 'music[evaluation]'
  });
  </script>

app/views/musics/index.html.erb
<div>
  <h2><%= flash[:notice]  %></h2>
</div>
<div class="iine">
  <h2>人気の楽曲</h2>
</div>
<br>
  <div class="container mt-5" >
    <div class="row justify-content: center;">
      <% @all_ranks.each.with_index(1) do |music, i| %>
        <div class="col-lg-4 col-md-4 mb-4">
          <!--変数iを順位,musicを変数-->
          <h4>第<%= i %>位</h4>
          <span>
            <%= link_to music_path(music.id) do %>
              <%= attachment_image_tag(music, :song_image, fallback: "no_image.jpg", class: "jacket-image") %>
            <% end %>
          </span>
          <span class="col-2 mt-5 mx-auto">
            <%= music.title %>
          </span><br>
          <span class="col-2 mt-5 mx-auto">
            <%= link_to music.user.name, user_path(music.user.id) %>さん
          </span>
          <br>
          <br>
        </div>
      <% end %>
    </div>
  </div>
<hr>
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      <div class="mainContents col-sm-9 col-sm-push-3 col-md-12 col-md-push-3 ">
        <h2 class="subtitle pb-4">新着楽曲</h2>
          <div class="row">
              <% @musics.each do |music| %>
                <%# binding.pry %>
                <div class="col-md-4 pb-4">
                  <div class="card shadow-sm" style="width: 100%; height: 26rem;">
                    <div>
                      <%= link_to music_path(music.id) do %>
                        <%= attachment_image_tag(music, :song_image, fallback: "no_image.jpg", class: "jacket-image") %>
                      <% end %>
                    </div>
                    <div class="mx-auto new-song">
                      <br><p class="mx-auto"><%= link_to music.title, music_path(music.id) %> / <%= link_to music.user.name, user_path(music.user.id) %></p>
                      <!--scr以降でaudioリンクを持ってきて、controls=""で再生プレイヤを表示-->
                      <p class="mx-auto"><audio src= "<%= music.song %>" controls="" class="audio-form"></p>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
        </div>
      </div>
    </div>
  </div>
<div class="container col-2 mt-5 mx-auto">
  <span>
    <%= paginate @musics %>
  </span>
</div>

app/views/musics/new.html.erb
<h4 class="mx-auto">
  <% if @music.errors.any? %>
    <Strong><%= @music.errors.count %>  errors occur!  :</Strong>
      <ul>
        <% @music.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
  <% end %>
</h4>

<div class="container">
  <div class="row ">
    <div class="mx-auto" >
      <div class="mx-auto">
          <h2 class="field form-group row">
           <div class="mx-auto col mb-3">
             投稿用フォーム
            </div>
          </h2>
        <%= form_with model: @music, local:true do |f| %>
          <div class="field form-group row">
            <div class="mx-auto col mb-3">
              <%= f.label :曲名, class:"form-label" %>
              <%= f.text_field :title, autofocus: true, autocomplete: "title", class:"form-control",required: true %>
            </div>
          </div>
          <div class="field form-group row">
            <div class="mx-auto col mb-3">
              <%= f.label :曲の説明, class:"form-label" %>
              <%= f.text_field :caption, autofocus: true, autocomplete: "caption", class:"form-control",required: true %>
            </div>
          </div>
          <div class="field form-group row">
              <div class="mx-auto col mb-3">
                <%= f.label :song_image, 'ジャケ写など' %><br>
                <%= f.attachment_field :song_image,autofocus: true, required: true %>
              </div>
            </div>
            <div class="field form-group row">
              <div class="mx-auto col mb-3">
                <%= f.label :song, '曲の選択' %><br>
                <%= f.file_field :song , :size => 140,autofocus: true, required: true %><br>
                <p6><strong>※外部サイトは使用できません。また、他人の転載は禁止です。</strong></p6>
              </div>
            </div>
            <br>
             <div class="field form-group row">
              <div class="mx-auto col mb-3">
                <div id="evaluate_stars">
                  <%= f.label :evaluation, '自己評価　　' %>
                </div>
              </div>
            </div>
            <br>
            <div class="container ">
               <div class="row">
                  <div class="mx-auto" >
                    <div class="actions">
                      <%= f.submit "曲を投稿", class: "btn btn-primary btn-xl" %>
                    </div>
                  </div>
                </div>
              </div>
                <% end %>
            </div>
        </div>
      </div>
    </div>
  </div>
  <!-- 評価javascript -->
 <script>
  $('#evaluate_stars').raty({
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    scoreName: 'music[evaluation]' //登録するモデル名とカラム名を記述
  });
</script>

app/views/musics/show.html.erb
<div>
  <h2><%= flash[:notice]  %></h2>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="song-image">
        <%= attachment_image_tag @music, :song_image, size: "300x300" %>
      </div>
    </div>

    <div class="col-md-6">
      <p>曲名：<%= @music.title %></p>
      <p>説明：<%= @music.caption %></p>
      <p>ユーザーネーム：<%= @music.user.name %></p>
      <p><audio src= "<%= "#{@music.song}" %>" controls=""></audio></p>
      <p>投稿日：<%= @music.created_at.strftime('%Y/%m/%d') %></p>
      <div>自己評価：
      <p class="song-evaluation" data-score="<%= @music.evaluation %>"></p></div>
        <script>
          $('.song-evaluation').empty();
          $('.song-evaluation').raty({
            readOnly: true,
            starOn: "<%= asset_path('star-on.png') %>",
            starOff: "<%= asset_path('star-off.png') %>",
            starHalf: "<%= asset_path('star-half.png') %>",
            score: function() {
              return $(this).attr('data-score');
            },
          });
        </script>
      <% if @music.user == current_user %>
        <%= link_to "編集", edit_music_path(@music.id) %>｜
        <%= link_to "削除", music_path(@music), method: :delete %>
      <% end %>
      <div id="favorite_buttons_<%= @music.id %>">
    　　<%= render "favorites/favorite", music: @music %>
　　  </div>
　  </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="music-show-profile">
        <% @music.comments.each do |comment| %>
          <p><%= attachment_image_tag comment.user, :profile_image,  size: "100x100", fallback: "no_image.jpg" %></p>
      </div>
      <div class="col-md-6">
          <span>ユーザーネーム：<%= link_to comment.user.name, user_path(comment.user.id) %></span><br>
          <span>コメント投稿日：<%= comment.created_at.strftime('%Y/%m/%d') %></span><br>
          <span class="comment"><%= comment.content %><br>
          <% if comment.user == current_user %></span>
          <div>
            <%= link_to "削除", music_comment_path(comment.music, comment), method: :delete %>
          </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="comment-form">
<%= form_with(model:[@music, @comment], local: true) do |f| %>
  <%= f.text_area :content,size: "45x3",placeholder: "コメントをここに" %><br>
  <%= f.submit "送信する", class: "btn btn-outline-primary" %>
<% end %>
</div>