config/routes.rb
Rails.application.routes.draw do
 root to: 'homes#top'
 get 'about' => 'homes#about'
 get 'search' => 'searches#search'
 devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 resources :musics do
  resource :favorites, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
 end

  resources :users, only: [:show] do
    get 'favorites' => "users#favorites"
  end
  resources :users do
  #memberでidを取得する
   member do
      get :follows, :followers
    end
  resource :relationships, only: [:create, :destroy]
   get 'followings' => 'relationships#followings', as: 'followings'
   get 'followers' => 'relationships#followers', as: 'followers'
   get 'musics' => 'users#music'
  end

  resources :contacts, only: [:new, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :music

end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true, length: {maximum:255},
                    format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
  validates :message, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

belongs_to :user
belongs_to :music

end

app/models/music.rb
class Music < ApplicationRecord

mount_uploader :song, AudiofileUploader

  belongs_to :user
  attachment :song_image
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def self.search(search, word)
    if word == ""
      @music = []
    elsif search == "perfect_match"
      @music = Music.where(title: word)
    elsif search == "partial_match"
      @music = Music.where("title LIKE?","%#{word}%")
    else
      @music = Music.all
    end
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :evaluation, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }

  validates :title, length: { in: 2..50 }, presence: true
  validates :caption, length: { in: 2..100 }, presence: true
  validates :song, presence: true
  validates :song_image, presence: true

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :musics, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_musics, through: :favorites, source: :music

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人


  attachment :profile_image

  def self.search(search,word)
    if word == ""
      @user = []
    elsif search == "perfect_match"
      @user = User.where(name: word)
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end
  validates :name,  presence: true
  validates :name, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    music = Music.find(params[:music_id])
    #currentuserの新規コメントをcontentと定義
    content = current_user.comments.new(comment_params)
    content.music_id = music.id
    content.save
    redirect_to music_path(music)
  end

  def destroy
    Comment.find_by(id: params[:id]).destroy
    redirect_to music_path(params[:music_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.send_mail(@contact).deliver
      flash[:notice] = 'お問い合わせを受け付けました。ありがとうございました。'
      redirect_to root_path
    else
      render :new
    end
  end

private

  def contact_params
    params.require(:contact).permit(:name, :email, :message)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :find_music, only: [:show, :edit, :update]

  def show
    @comment = Comment.new
  end

  def index
    @musics = Music.page(params[:page]).reverse_order
    @user = current_user
    #ランキング機能music_idをもってきて、favoritecountを表示。表示数を3件
    @all_ranks = Music.find(Favorite.group(:music_id).order('count(music_id) desc').limit(3).pluck(:music_id))
  end

  def new
    # Musicの新規投稿について定義
    @music = Music.new
  end

  def create
    @music = Music.new(music_params)
    # current_userをuserに紐づいているmusicと結びつける
    @music.user_id = current_user.id
    if @music.save
      redirect_to musics_path, notice: '投稿しました。'
      #binding.pry
    else
      render :new
    end
  end


  def edit
  end

  def update
    if @music.update(music_params)
      redirect_to music_path(@music.id), notice: '編集しました。'
    else
      render :edit
    end
  end

  def destroy
    @music = Music.find(params[:id])
    @music.destroy
    redirect_to musics_path
  end

  private
  def music_params
    params.require(:music).permit(:title, :caption, :song, :song_image, :user_id, :evaluation)
  end

  def find_music
    @music = Music.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @musics = @user.musics.page(params[:page]).reverse_order
    # id以外の値を取得するためwhereを使用　フォローしている人の楽曲をマイページのタイムラインに表示
    @feeds = Music.where(user_id: [current_user.id, *current_user.following_user_ids]).order(created_at: :desc)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: 'ユーザー情報を編集しました。'
    else
      render :edit
    end
  end

  def music
    @user = User.find(params["user_id"])
    # userが投稿した曲の表示
    @musics = @user.musics.page(params[:page]).reverse_order
    # id以外の値を取得するためwhereを使用　フォローしている人の楽曲をマイページのタイムラインに表示
    @feeds = Music.where(user_id: [current_user.id, *current_user.following_user_ids]).order(created_at: :desc)
    @following_users = @user.following_user
    @follower_users = @user.follower_user
  end

  def favorites
    @user = User.find(params["user_id"])
    # userがいいねした楽曲をfavoriteと定義
    favorites = Favorite.where(user_id: @user.id).pluck(:music_id)
    @favorite_musics = Music.find(favorites)
  end

  def follows
    # フォロー一覧ページ
    user = User.find(params[:id])
    @users = user.following_user.page(params[:page]).per(3).reverse_order
  end

  def followers
    # フォロワー一覧ページ
    user = User.find(params[:id])
    @users = user.follower_user.page(params[:page]).per(3).reverse_order
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container mt-5">
     <div class='row'>
        <div class='mx-auto'>
      <h1  class="footer-logo"><%= link_to image_tag("logo.png", height:"80px"), root_path %></h1>
      <p class="site-info">
          <span>BandHouse 　いつでもどこでも聴ける音楽</span><br>
          <span><%= link_to "お問い合わせフォーム", new_contact_path %></span>
      </p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
            <div class="col-2">
                <h1><%= link_to image_tag("logo.png", height:"100px"), root_path, class:"header-logo" %></h1>
            </div>
            <div class="col-3 search-form">
                 <% if user_signed_in? %>
                    <%= form_tag(search_path, method: :get) do %>
                        <%= text_field_tag (:word) %>
                　　      <%= select_tag 'range' ,options_for_select([['User', '1'], ['Music', '2']]) %>
                   　    <%= select_tag 'search', options_for_select([ ["完全一致","perfect_match"], ["部分一致","partial_match"]]) %>
                   　    <%= submit_tag "検索" %>
                    <% end %>
                <% end %>
            </div>
            <div class="col-7　ml-auto">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse ml-auto" id="navbarNavDropdown">
                    <ul class="navbar-nav  ml-auto">
                        <% if user_signed_in? %>
                          <li><%= link_to ' My Page', current_user, class: ' nav-link text-body' %></li>
                          <li><%= link_to ' Log Out', destroy_user_session_path, method: :delete,class: 'nav-link text-body' %></li>
                          <li><%= link_to ' New Post', new_music_path, class: ' nav-link text-body' %></li>
                          <li><%= link_to ' Music', musics_path ,class: 'nav-link text-body'%></li>
                        <% else %>
                          <li><%= link_to ' Sigh Up', new_user_registration_path,class: 'nav-link text-body' %></li>
                          <li><%= link_to ' Log In', new_user_session_path ,class: 'nav-link text-body'%></li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BandHouse</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render "layouts/header" %>
      <main>
        <%= yield %>
      </main>
    <%= render "layouts/footer" %>
    <span id="top-back">
  </body>
</html>